# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel
r_packages: ncdf4, sf
sudo: false
cache: packages
addons:
  apt:
    update: true
    packages:
      - librdf0-dev
      - libnetcdf-dev
      - netcdf-bin
