# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
dist: bionic
language: r
r:
  - oldrel
  - release
  - devel
r_packages:
  - ncdf4
  - sf
sudo: false
cache: packages
warnings_are_errors: false
addons:
  apt:
    update: true
    packages:
      - librdf0-dev
      - libnetcdf-dev
      - netcdf-bin
      - libudunits2-dev # for udunits2
      - libgeos-dev # for sf
      - libproj-dev # for sf
      - libgdal-dev # for sf
      - libjq-dev
      - libv8-dev
