# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel
sudo: false
cache: packages
r_binary_packages:
  - redland
  - ncdf4
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y librdf0-dev libnetcdf-dev
